spring.application.name=taskmanager
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=postgres
spring.datasource.password=MASKI
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
jwt.secret=your-very-long-secret-key-change-this-later
jwt.expiration=86400000